=== Taiizor/Store/src/SucroseInfoSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Sucrose Wallpaper Info Schema",
  "description": "JSON schema for defining wallpaper app information, including optional localization support.",
  "type": "object",
  "properties": {
    "AppVersion": {
      "type": "string",
      "description": "Version of the app."
    },
    "Version": {
      "type": "string",
      "description": "Version of the wallpaper."
    },
    "Title": {
      "type": "string",
      "description": "Title of the wallpaper.",
      "maxLength": 50
    },
    "Thumbnail": {
      "type": "string",
      "description": "Thumbnail image of the wallpaper."
    },
    "Preview": {
      "type": "string",
      "description": "Preview image or animation of the wallpaper."
    },
    "Description": {
      "type": "string",
      "description": "Description of the wallpaper.",
      "maxLength": 500
    },
    "Author": {
      "type": "string",
      "description": "Author of the wallpaper.",
      "maxLength": 50
    },
    "License": {
      "type": [
        "string",
        "null"
      ],
      "description": "License information for the wallpaper (string or null)."
    },
    "Contact": {
      "type": "string",
      "description": "Contact information for the wallpaper.",
      "maxLength": 250
    },
    "Type": {
      "type": "integer",
      "description": "Type of the wallpaper."
    },
    "Source": {
      "type": "string",
      "description": "Source location of the wallpaper."
    },
    "Tags": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 20
      },
      "minItems": 1,
      "maxItems": 5,
      "description": "Tags associated with the wallpaper (array or null)."
    },
    "Arguments": {
      "type": [
        "string",
        "null"
      ],
      "description": "Arguments for the wallpaper (string or null).",
      "maxLength": 250
    },
    "Localization": {
      "description": "Localized titles and descriptions for different languages (optional, dynamic keys like EN, TR, ES, etc.).",
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "object",
          "patternProperties": {
            "^[A-Z]{2,3}$": {
              "type": "object",
              "properties": {
                "Title": {
                  "type": "string",
                  "maxLength": 50,
                  "description": "Localized title."
                },
                "Description": {
                  "type": "string",
                  "maxLength": 500,
                  "description": "Localized description."
                }
              },
              "required": [
                "Title",
                "Description"
              ],
              "additionalProperties": false
            }
          },
          "minProperties": 1,
          "additionalProperties": false
        }
      ]
    }
  },
  "required": [
    "AppVersion",
    "Version",
    "Title",
    "Thumbnail",
    "Preview",
    "Description",
    "Author",
    "License",
    "Contact",
    "Type",
    "Source",
    "Tags",
    "Arguments"
  ],
  "additionalProperties": false
}

=== Taiizor/Store/src/Fantasy/Going Through Hard Time-1/SucroseInfo.json
{
  "AppVersion": "24.7.17.0",
  "Version": "1.0.0.0",
  "Title": "Going Through Hard Time",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Going Through Hard Time - Live Wallpaper",
  "Author": "Ï€ Wallpapers",
  "License": null,
  "Contact": "https://www.youtube.com/@Pi_Wallpapers",
  "Type": 3,
  "Source": "gtht.mp4",
  "Tags": null,
  "Arguments": null
}

=== Taiizor/Store/src/Film and TV/Spider Man-1/SucroseInfo.json
{
  "AppVersion": "24.7.1.0",
  "Version": "1.0.0.2",
  "Title": "Spider Man",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Spider Man - Miles Morales - 4K",
  "Author": "Live Wallpaper",
  "License": null,
  "Contact": "https://www.youtube.com/@live_wallpaper3479",
  "Type": 3,
  "Source": "milesm.mp4",
  "Tags": null,
  "Arguments": null
}

=== Taiizor/Store/src/Game/Ayleid Ruins-1/SucroseInfo.json
{
  "AppVersion": "24.7.3.0",
  "Version": "1.0.0.0",
  "Title": "Ayleid Ruins",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Ayleid Ruins - The Elder Scrolls IV Oblivion - Live Wallpaper",
  "Author": "MoeWalls",
  "License": null,
  "Contact": "https://moewalls.com/games/ayleid-ruins-the-elder-scrolls-iv-oblivion-live-wallpaper",
  "Type": 3,
  "Source": "artesivo.mp4",
  "Tags": [
    "Falling Leaves",
    "Jungle",
    "Birds",
    "River",
    "Boat"
  ],
  "Arguments": null
}

=== Taiizor/Store/src/Film and TV/Kylo Ren-1/SucroseInfo.json
{
  "AppVersion": "24.2.24.0",
  "Version": "1.0.0.1",
  "Title": "Kylo Ren",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Kylo Ren - Star Wars The Last Jedi",
  "Author": "SeveronJ",
  "License": null,
  "Contact": "https://www.youtube.com/@SeveronJ",
  "Type": 3,
  "Source": "kyloren.mp4",
  "Tags": null,
  "Arguments": null
}

=== Taiizor/Store/src/Game/Elderwood Gnar-1/SucroseInfo.json
{
  "AppVersion": "24.7.17.0",
  "Version": "1.0.0.0",
  "Title": "Elderwood Gnar",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Elderwood Gnar - League of Legends - Live Wallpaper",
  "Author": "Ï€ Wallpapers",
  "License": null,
  "Contact": "https://www.youtube.com/@Pi_Wallpapers",
  "Type": 3,
  "Source": "eglol.mp4",
  "Tags": null,
  "Arguments": null
}

=== Taiizor/Store/src/War/Kylo Ren's Lightsaber-1/SucroseInfo.json
{
  "AppVersion": "24.7.1.0",
  "Version": "1.0.0.2",
  "Title": "Kylo Ren's Lightsaber",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Kylo Ren's Lightsaber Ignition - Star Wars",
  "Author": "Raphael Hodjaev",
  "License": null,
  "Contact": "https://www.youtube.com/@rapflapfl",
  "Type": 3,
  "Source": "krli.mp4",
  "Tags": null,
  "Arguments": null
}

=== Taiizor/Store/src/Game/God of War-2/SucroseInfo.json
{
  "AppVersion": "24.7.1.0",
  "Version": "1.0.0.2",
  "Title": "God of War",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "God of War 2018 4K",
  "Author": "Gus Blackk",
  "License": null,
  "Contact": "https://www.youtube.com/@gusblackk2013",
  "Type": 3,
  "Source": "gow.mp4",
  "Tags": null,
  "Arguments": null
}

=== Taiizor/Store/src/Anime/Apple-1/SucroseInfo.json
{
  "AppVersion": "24.9.21.0",
  "Version": "1.0.0.0",
  "Title": "Apple",
  "Thumbnail": "thumbnail.jpg",
  "Preview": "preview.gif",
  "Description": "Apple - Death Note - Live Wallpaper",
  "Author": "DesktopHut",
  "License": null,
  "Contact": "https://www.desktophut.com/death-note-apple",
  "Type": 3,
  "Source": "adn.mp4",
  "Tags": [
    "Red Apple",
    "Shinigami",
    "Eerie",
    "Kira",
    "Ryuk"
  ],
  "Arguments": null
}
